# https://github.com/drdoctr/doctr
# doctr requires python >=3.5
language: python
python:
  - 3.6

# This gives doctr the key we've generated
sudo: false
env:
  global:
    secure: "D2fkStwPUFK0cAgId5KZ0/+KBcflkxu2icQjO8lXmLCc4VHjIWlz4vUPoldJSzHqL3LPdHJfVs3qCOqrqOFXwTU7zIylNMx7rPe7UO9TcGKPQSEQXu05zSIVvaMS00vTfB5rUuMQfGXh59jcWtIeMfGNc34ZjuPe9xPE+iKqwk5EtkJBDbxQ+3xxJn1hWC9J3EqHiXGoMlPXO34svSOIGTCIN2XTgF4QAvdxpUqwYQqdTwIiu5ckCBl0oZSQ844lHP7m+AcUDcswuzrFcg4y/qvzfVcDWu++AopnFuKN2fO4ti4X1tLX5zUAQerDX9YXITWm9CRgd0SLGNDYE5IqIawRIZxMiLZGI92M1xgNsOeypuucahDB7xXCVtJwPCJUXVulHI18M+zYAC+i3ZtoS/sMPNEXnlfycmQqXrn4Soe+UoA5X0LR4l3wbOgankyRh2DwIAABSsqjHY8tU/5c6ZyIuJzLR+AcwUoxilP5DO0Xji9OlIiXWfQK9XVfNVqhoru++NMKorlzgEARC/aVX4X8/vvm+bh2TZI/8iFIMS0gj9PEEjkv5oOduInMuiofzrm+U4BO29ZbVEZtgawJKFlZusEW6nURgysNKQZjroMqjOH+iuKWWfmpShwFeKQmQMsm1PcObTfDEBRZIZeNSbUJpo7MTR34JuZpm2o5snY="
# This is the script to build the docs on travis, then deploy
script:
  - set -e
  - pip install doctr pelican jupyter ipython nbconvert beautifulsoup4 markdown
  - make DEBUG=1 html
  - doctr deploy . --built-docs output/
